# Generated by Django 4.1.3 on 2022-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappstaff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_durable",
            name="image",
            field=models.ImageField(upload_to="Durable"),
        ),
        migrations.AlterField(
            model_name="add_parcel",
            name="image",
            field=models.ImageField(upload_to="Parcel"),
        ),
    ]
