# Generated by Django 4.1.3 on 2022-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0003_categorydisplay_categorymenu_categorystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydisplay',
            name='name_CategoryDisplay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categorymenu',
            name='name_CategoryMenu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorystatus',
            name='name_CategoryStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='name_CategoryType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
