# Generated by Django 4.1.3 on 2022-11-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0004_alter_categorydisplay_name_categorydisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_durable',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myappstaff.categorymenu'),
        ),
        migrations.AddField(
            model_name='add_parcel',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myappstaff.categorymenu'),
        ),
        migrations.AlterField(
            model_name='add_durable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myappstaff.categorytype'),
        ),
        migrations.AlterField(
            model_name='add_parcel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myappstaff.categorytype'),
        ),
    ]
