# Generated by Django 4.1.3 on 2022-11-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0005_add_durable_menu_add_parcel_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_parcel',
            old_name='category',
            new_name='categoryType',
        ),
    ]
