# Generated by Django 4.1.3 on 2022-11-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myappstaff", "0006_rename_category_add_parcel_categorytype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add_parcel", old_name="categoryType", new_name="category",
        ),
    ]
