# Generated by Django 4.1.3 on 2022-12-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myappstaff", "0007_rename_categorytype_add_parcel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_durable",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_durable",
                to="myappstaff.categorytype",
            ),
        ),
        migrations.AlterField(
            model_name="add_durable",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_durable",
                to="myappstaff.categorymenu",
            ),
        ),
        migrations.AlterField(
            model_name="add_parcel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_parcel",
                to="myappstaff.categorytype",
            ),
        ),
        migrations.AlterField(
            model_name="add_parcel",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_parcel",
                to="myappstaff.categorymenu",
            ),
        ),
    ]
