# Generated by Django 4.1.3 on 2022-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0008_alter_add_durable_category_alter_add_durable_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
