# Generated by Django 4.1.3 on 2022-12-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0010_add_phone_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryDisplay',
        ),
        migrations.RemoveField(
            model_name='add_durable',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='add_parcel',
            name='menu',
        ),
        migrations.DeleteModel(
            name='CategoryMenu',
        ),
    ]
