# Generated by Django 4.1.3 on 2022-12-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0011_delete_categorydisplay_remove_add_durable_menu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Phone',
        ),
    ]
