# Generated by Django 4.1.3 on 2022-12-12 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappstaff', '0013_add_durable_username_add_parcel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVE', 'รับเรื่อง'), ('INPROGRESS', 'กำลังดำเนินการ'), ('FINISH', 'ดำเนินการเสร็จสิ้น')], max_length=40, verbose_name='Status')),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
