# Generated by Django 4.1.3 on 2022-12-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0014_status_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_durable',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_durable', to='myappstaff.categorystatus'),
        ),
        migrations.AddField(
            model_name='add_parcel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_parcel', to='myappstaff.categorystatus'),
        ),
    ]
