# Generated by Django 4.1.3 on 2022-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0017_rename_status_status_confirm_status_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_confirm',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status_deny',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
