# Generated by Django 4.1.3 on 2022-12-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0018_status_confirm_status_status_deny_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_Deny',
        ),
    ]
