# Generated by Django 4.1.3 on 2022-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0019_delete_status_deny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_confirm',
            name='status_confirm',
        ),
    ]
