# Generated by Django 4.1.3 on 2022-12-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0020_remove_status_confirm_status_confirm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_Confirm',
        ),
    ]
