# Generated by Django 4.1.3 on 2022-12-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0022_status_rec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_rec',
        ),
    ]
