# Generated by Django 4.1.3 on 2022-12-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0023_delete_status_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_parcel',
            name='numdate',
        ),
    ]
