# Generated by Django 4.1.3 on 2022-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0024_remove_add_parcel_numdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_durable',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='add_parcel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
