# Generated by Django 4.1.3 on 2022-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Staff_Email_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_staff', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_User_Email_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
