# Generated by Django 4.1.3 on 2022-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappSuper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.CharField(max_length=500, null=True)),
                ('position', models.CharField(choices=[('user', 'USER'), ('staff', 'STAFF'), ('admin', 'ADMIN')], default='user', max_length=6)),
                ('phone', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
