# Generated by Django 4.1.3 on 2022-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappSuper', '0002_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
