# Generated by Django 4.1.3 on 2022-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappSuper', '0005_alter_add_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_user',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
