# Generated by Django 4.1.3 on 2022-12-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappSuper', '0007_alter_add_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Staff_Email_User',
        ),
        migrations.DeleteModel(
            name='Add_User',
        ),
        migrations.DeleteModel(
            name='Add_User_Email_User',
        ),
    ]
