# Generated by Django 4.1.3 on 2022-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listrec',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listrec',
            name='quantity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
