# Generated by Django 4.1.3 on 2022-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_listrec_listfromrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
