# Generated by Django 4.1.3 on 2022-11-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_listfromrec_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
