# Generated by Django 4.1.3 on 2022-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_listfromrec_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
