# Generated by Django 4.1.3 on 2022-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_listfromrec_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='link',
            field=models.URLField(blank=True, default=None),
        ),
    ]
