# Generated by Django 4.1.3 on 2022-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_listfromrec_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
