# Generated by Django 4.1.3 on 2022-11-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_listfromrec_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='price',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
