# Generated by Django 4.1.3 on 2022-11-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_listfromrec_price_alter_listfromrec_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
