# Generated by Django 4.1.3 on 2022-12-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_listfromrec_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="listfromrec",
            name="datetime",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
