# Generated by Django 4.1.3 on 2022-12-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_contact_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
