# Generated by Django 4.1.3 on 2022-12-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_contact_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_user',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='brand',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='listfromrec',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
