# Generated by Django 4.1.3 on 2022-12-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_contact_contact_user_alter_listfromrec_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfromrec',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
