# Generated by Django 4.1.3 on 2022-12-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_listfromrec_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listfromrec',
            name='status',
        ),
    ]
