# Generated by Django 4.1.3 on 2022-12-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_listfromrec_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfromrec',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
