# Generated by Django 4.1.3 on 2022-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_listfromrec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfromrec',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
