# Generated by Django 4.1.3 on 2022-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_actor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=bool, serialize=False)),
            ],
        ),
    ]
