# Generated by Django 4.1.3 on 2022-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=bool, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Add_actor',
            new_name='Add_Staff',
        ),
    ]
