# Generated by Django 4.1.3 on 2022-12-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappAdmin', '0004_rename_email_add_admin_email_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Admin',
        ),
    ]
